<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'addToBottom' => false,
'delete' => true,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'username' => array( 'totalsType' => '' ),
'password' => array( 'totalsType' => '' ),
'fullname' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'isactive' => array( 'totalsType' => '' ),
'add_user' => array( 'totalsType' => '' ),
'add_date' => array( 'totalsType' => '' ),
'edit_user' => array( 'totalsType' => '' ),
'edit_date' => array( 'totalsType' => '' ),
'ext_security_id' => array( 'totalsType' => '' ),
'm_employee_id' => array( 'totalsType' => '' ),
'last_login_date' => array( 'totalsType' => '' ),
'apikey' => array( 'totalsType' => '' ),
'is_active' => array( 'totalsType' => '' ),
'is_delete' => array( 'totalsType' => '' ),
'deleted_date' => array( 'totalsType' => '' ),
'created_date' => array( 'totalsType' => '' ),
'created_by' => array( 'totalsType' => '' ),
'last_update_by' => array( 'totalsType' => '' ),
'last_update_date' => array( 'totalsType' => '' ),
'userpic' => array( 'totalsType' => '' ),
'url_calender' => array( 'totalsType' => '' ),
'two_factor' => array( 'totalsType' => '' ),
'totp' => array( 'totalsType' => '' ),
'reset_token' => array( 'totalsType' => '' ),
'reset_date' => array( 'totalsType' => '' ),
'phone' => array( 'totalsType' => '' ),
'login_type' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'username',
'password',
'fullname',
'email',
'isactive',
'add_user',
'add_date',
'edit_user',
'edit_date',
'ext_security_id',
'm_employee_id',
'last_login_date',
'apikey',
'is_active',
'is_delete',
'deleted_date',
'created_date',
'created_by',
'last_update_by',
'last_update_date',
'userpic',
'url_calender',
'two_factor',
'totp',
'reset_token',
'reset_date',
'phone',
'login_type' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'add_date',
'userpic',
'username',
'url_calender',
'two_factor',
'totp',
'reset_token',
'reset_date',
'phone',
'password',
'm_employee_id',
'login_type',
'last_update_date',
'last_update_by',
'last_login_date',
'isactive',
'is_delete',
'is_active',
'id',
'fullname',
'ext_security_id',
'email',
'edit_user',
'edit_date',
'deleted_date',
'created_date',
'created_by',
'apikey',
'add_user' ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'username',
'password',
'fullname',
'email',
'isactive',
'add_user',
'add_date',
'edit_user',
'edit_date',
'ext_security_id',
'm_employee_id',
'last_login_date',
'apikey',
'is_active',
'is_delete',
'deleted_date',
'created_date',
'created_by',
'last_update_by',
'last_update_date',
'userpic',
'url_calender',
'two_factor',
'totp',
'reset_token',
'reset_date',
'phone',
'login_type' ),
'inlineEditFields' => array( 'username',
'password',
'fullname',
'email',
'isactive',
'add_user',
'add_date',
'edit_user',
'edit_date',
'ext_security_id',
'm_employee_id',
'last_login_date',
'apikey',
'is_active',
'is_delete',
'deleted_date',
'created_date',
'created_by',
'last_update_by',
'last_update_date',
'userpic',
'url_calender',
'two_factor',
'totp',
'reset_token',
'reset_date',
'phone',
'login_type' ),
'fieldItems' => array( 'id' => array( 'simple_grid_field',
'simple_grid_field29' ),
'username' => array( 'simple_grid_field1',
'simple_grid_field30' ),
'password' => array( 'simple_grid_field2',
'simple_grid_field31' ),
'fullname' => array( 'simple_grid_field3',
'simple_grid_field32' ),
'email' => array( 'simple_grid_field4',
'simple_grid_field33' ),
'isactive' => array( 'simple_grid_field5',
'simple_grid_field34' ),
'add_user' => array( 'simple_grid_field6',
'simple_grid_field35' ),
'add_date' => array( 'simple_grid_field7',
'simple_grid_field36' ),
'edit_user' => array( 'simple_grid_field8',
'simple_grid_field37' ),
'edit_date' => array( 'simple_grid_field9',
'simple_grid_field38' ),
'ext_security_id' => array( 'simple_grid_field10',
'simple_grid_field39' ),
'm_employee_id' => array( 'simple_grid_field11',
'simple_grid_field40' ),
'last_login_date' => array( 'simple_grid_field12',
'simple_grid_field41' ),
'apikey' => array( 'simple_grid_field13',
'simple_grid_field42' ),
'is_active' => array( 'simple_grid_field14',
'simple_grid_field43' ),
'is_delete' => array( 'simple_grid_field15',
'simple_grid_field44' ),
'deleted_date' => array( 'simple_grid_field16',
'simple_grid_field45' ),
'created_date' => array( 'simple_grid_field17',
'simple_grid_field46' ),
'created_by' => array( 'simple_grid_field18',
'simple_grid_field47' ),
'last_update_by' => array( 'simple_grid_field19',
'simple_grid_field48' ),
'last_update_date' => array( 'simple_grid_field20',
'simple_grid_field49' ),
'userpic' => array( 'simple_grid_field21',
'simple_grid_field50' ),
'url_calender' => array( 'simple_grid_field22',
'simple_grid_field51' ),
'two_factor' => array( 'simple_grid_field23',
'simple_grid_field52' ),
'totp' => array( 'simple_grid_field24',
'simple_grid_field53' ),
'reset_token' => array( 'simple_grid_field25',
'simple_grid_field54' ),
'reset_date' => array( 'simple_grid_field26',
'simple_grid_field55' ),
'phone' => array( 'simple_grid_field27',
'simple_grid_field56' ),
'login_type' => array( 'simple_grid_field28',
'simple_grid_field57' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'delete',
'details_found',
'page_size' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ),
'top' => array(  ),
'grid' => array( 'simple_grid_field29',
'simple_grid_field',
'simple_grid_field30',
'simple_grid_field1',
'simple_grid_field31',
'simple_grid_field2',
'simple_grid_field32',
'simple_grid_field3',
'simple_grid_field33',
'simple_grid_field4',
'simple_grid_field34',
'simple_grid_field5',
'simple_grid_field35',
'simple_grid_field6',
'simple_grid_field36',
'simple_grid_field7',
'simple_grid_field37',
'simple_grid_field8',
'simple_grid_field38',
'simple_grid_field9',
'simple_grid_field39',
'simple_grid_field10',
'simple_grid_field40',
'simple_grid_field11',
'simple_grid_field41',
'simple_grid_field12',
'simple_grid_field42',
'simple_grid_field13',
'simple_grid_field43',
'simple_grid_field14',
'simple_grid_field44',
'simple_grid_field15',
'simple_grid_field45',
'simple_grid_field16',
'simple_grid_field46',
'simple_grid_field17',
'simple_grid_field47',
'simple_grid_field18',
'simple_grid_field48',
'simple_grid_field19',
'simple_grid_field49',
'simple_grid_field20',
'simple_grid_field50',
'simple_grid_field21',
'simple_grid_field51',
'simple_grid_field22',
'simple_grid_field52',
'simple_grid_field23',
'simple_grid_field53',
'simple_grid_field24',
'simple_grid_field54',
'simple_grid_field25',
'simple_grid_field55',
'simple_grid_field26',
'simple_grid_field56',
'simple_grid_field27',
'simple_grid_field57',
'simple_grid_field28',
'grid_checkbox_head',
'grid_checkbox' ) ),
'formXtTags' => array( 'above-grid' => array( 'deleteselected_link',
'details_found',
'recsPerPage' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'simple_grid_field29' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field28' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid' ),
'itemLocations' => array( 'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field26',
'search_panel_field27',
'search_panel_field28' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'notifications' => array( 'notifications' ),
'-' => array( '-',
'-1',
'-2',
'-3' ),
'delete' => array( 'delete' ),
'delete_selected' => array( 'delete_selected' ),
'advsearch_link' => array( 'advsearch_link' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28' ),
'grid_field_label' => array( 'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'username_fieldheadercolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'password_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'fullname_fieldheadercolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'email_fieldheadercolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'isactive_fieldheadercolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'add_user_fieldheadercolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'add_date_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'edit_user_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'edit_date_fieldheadercolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'ext_security_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'm_employee_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'last_login_date_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'apikey_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'is_active_fieldheadercolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'is_delete_fieldheadercolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'deleted_date_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'created_date_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'created_by_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'last_update_by_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'last_update_date_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'userpic_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'url_calender_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'two_factor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'totp_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'reset_token_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'reset_date_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'phone_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'login_type_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'id_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'username_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'password_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'fullname_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'email_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'isactive_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'add_user_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'add_date_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'edit_user_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'edit_date_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'ext_security_id_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'm_employee_id_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'last_login_date_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'apikey_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'is_active_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'is_delete_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'deleted_date_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'created_date_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'created_by_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'last_update_by_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'last_update_date_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'userpic_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'url_calender_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'two_factor_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'totp_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'reset_token_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'reset_date_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'phone_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'login_type_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 30,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'delete' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'id',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'id',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'username',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'username',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'password',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'password',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'fullname',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'fullname',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'email',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'email',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'isactive',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'isactive',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'add_user',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'add_user',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'add_date',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'add_date',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'edit_user',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'edit_user',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'edit_date',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'edit_date',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'ext_security_id',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'ext_security_id',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'm_employee_id',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'm_employee_id',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'last_login_date',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'last_login_date',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'apikey',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'apikey',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'is_active',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'is_active',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'is_delete',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'is_delete',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'deleted_date',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'deleted_date',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'created_date',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'created_date',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'created_by',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'created_by',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'last_update_by',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'last_update_by',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'last_update_date',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'last_update_date',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'userpic',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'userpic',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'url_calender',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'url_calender',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'two_factor',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'two_factor',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'totp',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'totp',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'reset_token',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'reset_token',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'reset_date',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'reset_date',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'phone',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'phone',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'login_type',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'login_type',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'delete_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'add_date',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field1' => array( 'field' => 'add_user',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field2' => array( 'field' => 'apikey',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field3' => array( 'field' => 'created_by',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field4' => array( 'field' => 'created_date',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field5' => array( 'field' => 'deleted_date',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field6' => array( 'field' => 'edit_date',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field7' => array( 'field' => 'edit_user',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field8' => array( 'field' => 'email',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field9' => array( 'field' => 'ext_security_id',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field10' => array( 'field' => 'fullname',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field11' => array( 'field' => 'id',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field12' => array( 'field' => 'is_active',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field13' => array( 'field' => 'is_delete',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field14' => array( 'field' => 'isactive',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field15' => array( 'field' => 'last_login_date',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field16' => array( 'field' => 'last_update_by',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field17' => array( 'field' => 'last_update_date',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field18' => array( 'field' => 'login_type',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field19' => array( 'field' => 'm_employee_id',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field20' => array( 'field' => 'password',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field21' => array( 'field' => 'phone',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field22' => array( 'field' => 'reset_date',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field23' => array( 'field' => 'reset_token',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field24' => array( 'field' => 'totp',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field25' => array( 'field' => 'two_factor',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field26' => array( 'field' => 'url_calender',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field27' => array( 'field' => 'username',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'notifications' => array( 'type' => 'notifications' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'delete' => array( 'type' => 'delete' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-3' => array( 'type' => '-' ),
'search_panel_field28' => array( 'field' => 'userpic',
'type' => 'search_panel_field' ),
'simple_grid_field' => array( 'field' => 'id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'id' ),
'simple_grid_field1' => array( 'field' => 'username',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field30' => array( 'type' => 'grid_field_label',
'field' => 'username' ),
'simple_grid_field2' => array( 'field' => 'password',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'password' ),
'simple_grid_field3' => array( 'field' => 'fullname',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field32' => array( 'type' => 'grid_field_label',
'field' => 'fullname' ),
'simple_grid_field4' => array( 'field' => 'email',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field33' => array( 'type' => 'grid_field_label',
'field' => 'email' ),
'simple_grid_field5' => array( 'field' => 'isactive',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field34' => array( 'type' => 'grid_field_label',
'field' => 'isactive' ),
'simple_grid_field6' => array( 'field' => 'add_user',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field35' => array( 'type' => 'grid_field_label',
'field' => 'add_user' ),
'simple_grid_field7' => array( 'field' => 'add_date',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'add_date' ),
'simple_grid_field8' => array( 'field' => 'edit_user',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'edit_user' ),
'simple_grid_field9' => array( 'field' => 'edit_date',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field38' => array( 'type' => 'grid_field_label',
'field' => 'edit_date' ),
'simple_grid_field10' => array( 'field' => 'ext_security_id',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field39' => array( 'type' => 'grid_field_label',
'field' => 'ext_security_id' ),
'simple_grid_field11' => array( 'field' => 'm_employee_id',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'm_employee_id' ),
'simple_grid_field12' => array( 'field' => 'last_login_date',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'last_login_date' ),
'simple_grid_field13' => array( 'field' => 'apikey',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'apikey' ),
'simple_grid_field14' => array( 'field' => 'is_active',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field43' => array( 'type' => 'grid_field_label',
'field' => 'is_active' ),
'simple_grid_field15' => array( 'field' => 'is_delete',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field44' => array( 'type' => 'grid_field_label',
'field' => 'is_delete' ),
'simple_grid_field16' => array( 'field' => 'deleted_date',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'deleted_date' ),
'simple_grid_field17' => array( 'field' => 'created_date',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'created_date' ),
'simple_grid_field18' => array( 'field' => 'created_by',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'created_by' ),
'simple_grid_field19' => array( 'field' => 'last_update_by',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'last_update_by' ),
'simple_grid_field20' => array( 'field' => 'last_update_date',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'last_update_date' ),
'simple_grid_field21' => array( 'field' => 'userpic',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'userpic' ),
'simple_grid_field22' => array( 'field' => 'url_calender',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'url_calender' ),
'simple_grid_field23' => array( 'field' => 'two_factor',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'two_factor' ),
'simple_grid_field24' => array( 'field' => 'totp',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'totp' ),
'simple_grid_field25' => array( 'field' => 'reset_token',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'reset_token' ),
'simple_grid_field26' => array( 'field' => 'reset_date',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'reset_date' ),
'simple_grid_field27' => array( 'field' => 'phone',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'phone' ),
'simple_grid_field28' => array( 'field' => 'login_type',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'login_type' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>