<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 't_booking_id',
't_booking_destination',
't_booking_remarks',
'm_vehicle_id',
'm_vehicle_driver',
't_booking_from_date',
't_booking_to_date',
'Voucher' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 't_booking_id' => array( 'import_field' ),
't_booking_destination' => array( 'import_field6' ),
't_booking_remarks' => array( 'import_field7' ),
'm_vehicle_id' => array( 'import_field13' ),
'm_vehicle_driver' => array( 'import_field1' ),
't_booking_from_date' => array( 'import_field2' ),
't_booking_to_date' => array( 'import_field3' ),
'Voucher' => array( 'import_field4' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field6',
'import_field7',
'import_field13',
'import_field1',
'import_field2',
'import_field3',
'import_field4' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field13' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field6',
'import_field7',
'import_field13',
'import_field1',
'import_field2',
'import_field3',
'import_field4' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field6',
'import_field7',
'import_field13',
'import_field1',
'import_field2',
'import_field3',
'import_field4' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 't_booking_id',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 't_booking_destination',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 't_booking_remarks',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'm_vehicle_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'm_vehicle_driver',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 't_booking_from_date',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 't_booking_to_date',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Voucher',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>