<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 't_meeting_user',
't_meeting_desc',
'user_participant_list',
't_meeting_participant_type',
't_meeting_total_participant',
't_meeting_roomid',
't_meeting_from_date',
't_meeting_to_date' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 't_meeting_roomid' => array( 'import_field1' ),
't_meeting_user' => array( 'import_field2' ),
't_meeting_desc' => array( 'import_field3' ),
't_meeting_from_date' => array( 'import_field4' ),
't_meeting_to_date' => array( 'import_field5' ),
'user_participant_list' => array( 'import_field9' ),
't_meeting_participant_type' => array( 'import_field10' ),
't_meeting_total_participant' => array( 'import_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field2',
'import_field3',
'import_field9',
'import_field10',
'import_field11',
'import_field1',
'import_field4',
'import_field5' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field1' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field9',
'import_field10',
'import_field11' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field2',
'import_field3',
'import_field9',
'import_field10',
'import_field11',
'import_field1',
'import_field4',
'import_field5' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 't_meeting_roomid',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 't_meeting_user',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 't_meeting_desc',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 't_meeting_from_date',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 't_meeting_to_date',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'user_participant_list',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 't_meeting_participant_type',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 't_meeting_total_participant',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>