<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_m_disposition_type  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessRowList"]=true;

		$this->events["BeforeMoveNextList"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before record processed
function BeforeProcessRowList(&$data, $pageObject)
{

		$userName = $_SESSION["userId"];
$idTicket = $data['t_disposition_no'];
$lastUser = $data['t_disposition_to'];

if($userName == $lastUser){
	$pageObject->showItem("add");
}else{
	$pageObject->hideItem("add");
}

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function BeforeProcessRowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		$userName = $_SESSION["userId"];
$lastUser = $data['t_disposition_to'];

if($userName == $lastUser){
	$pageObject->showItem("add", $recordId);
}else{
	$pageObject->hideItem("add", $recordId);
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>