<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'table' => array( 'connId' => 'u736239518tsundbat154412412',
'table' => 'm_login' ),
'usernameField' => 'username',
'userpicField' => '' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'r8JbtVfKHLIMev8dWdQd',
'JWTSecret' => 'lqQALBbpL6kQyfV4Y9lL',
'forceExpire' => false,
'keepAlive' => true ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 0,
'hashAlgorithm' => 0,
'registerPage' => false ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'no-reply@talisman.co.id',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'smtp-mail.outlook.com',
'SMTPPort' => 587,
'SMTPUser' => 'no-reply@talisman.co.id',
'SMTPPassword' => 'No2019reply!',
'securityProtocol' => 2 ),
'advancedSecurity' => array( 'allowGuestLogin' => false ),
'auditAndLocking' => array( 'loggingTable' => array(  ),
'lockingTable' => array(  ),
'tables' => array(  ),
'loggingMode' => 0,
'loggingFile' => 'audit.log',
'logSecurityActions' => false,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'TBooking',
'loginDataSource' => 'm_login',
'loginForm' => 0,
'dynamicPermissions' => false,
'dpTablePrefix' => '',
'dpTableConnId' => '',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'table' => array( 'connId' => 'u736239518tsundbat154412412',
'table' => 'm_login' ),
'usernameField' => 'username',
'userpicField' => '' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array( 'enabled' => true,
'table' => array( 'connId' => 'u736239518tsundbat154412412',
'table' => 'tsun_noti' ) ) );
?>